development:
  twitter:
    consumer_key: cYIXMfIFbrbUaPFpIDn4g
    consumer_secret: MBPv405HNlVIzir7szKyjzcisu4LdC2Pudg6Ka3lpjo

test:
  twitter:
    consumer_key: cYIXMfIFbrbUaPFpIDn4g
    consumer_secret: MBPv405HNlVIzir7szKyjzcisu4LdC2Pudg6Ka3lpjo

production:
  twitter:
    consumer_key: cYIXMfIFbrbUaPFpIDn4g
    consumer_secret: MBPv405HNlVIzir7szKyjzcisu4LdC2Pudg6Ka3lpjo
